// NOTE: This file is generated by Next.js. Do not edit this file directly.
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// If you need to extend NextAuth types, put those augmentations in:
//   src/types/next-auth.d.ts
